server:
  port: 8080

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Mysql@12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
  zipkin:
    base-url: http://localhost:9411/api/v2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-deovb4mrmkubde25.us.auth0.com/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

